/**
 * LeftControlPanel - Linke Seite des Split-Screen Editors
 *
 * Clean Design nach UX-Audit:
 * - Dokumenttitel (editierbar)
 * - Formularfelder (IMMER sichtbar, nicht collapsible)
 * - Textbausteine (kompakter Link mit Modal)
 * - Anlagen (kompakter Link mit Modal)
 * - Export-Buttons
 *
 * v5.0: Aufgeräumtes Design - keine Akkordeons mehr
 */

import { useState, useCallback, useRef, useEffect } from "react";
import { Users, Layers, Paperclip, ChevronRight } from "lucide-react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { useWizardContext } from "../WizardContext";
import { FormFieldsSection } from "./FormFieldsSection";
import { DynamicFieldsSection } from "./DynamicFieldsSection";
import { ClauseSelectionSection } from "./ClauseSelectionSection";
import { ActionBar } from "./ActionBar";
import { AttachmentSelector } from "../AttachmentSelector";
import { StationeryPicker } from "./StationeryPicker";
import { WorkflowDots } from "../WorkflowDots";
import { ToneSegmented } from "../ToneSegmented";
import { useMagicFill } from "@/hooks/useMagicFill";
import { ConsistencyBanner } from "../ConsistencyBanner";
import { ComplianceRiskBanner } from "../ComplianceRiskBanner";

interface DocumentType {
    id: number;
    name: string;
    country_code?: string;
    category?: string;
}

interface LeftControlPanelProps {
    documentTypes: DocumentType[];
}

export const LeftControlPanel = ({ documentTypes }: LeftControlPanelProps) => {
    const { state, actions } = useWizardContext();
    const { documentTitle, documentTypeId, documentClauses, selectedAttachmentIds, formData } = state;
    const nachname = formData.nachname as string | undefined;
    const vorname = formData.vorname as string | undefined;

    // Modal states für Textbausteine und Anlagen
    const [showClausesModal, setShowClausesModal] = useState(false);
    const [showAttachmentsModal, setShowAttachmentsModal] = useState(false);

    const selectedDocumentType = documentTypes.find(t => t.id === documentTypeId);

    // ── Auto-Naming (DS v2.1 §7) ─────────────────────────────────────────
    const prevAutoTitle = useRef("");

    useEffect(() => {
        if (!selectedDocumentType) return;

        const typeName = selectedDocumentType.name;
        let autoTitle: string;

        if (nachname && vorname) {
            autoTitle = `${typeName} – ${nachname}, ${vorname}`;
        } else if (nachname) {
            autoTitle = `${typeName} – ${nachname}`;
        } else {
            autoTitle = `${typeName} – ${new Date().toLocaleDateString("de-DE")}`;
        }

        // Update title only if empty or still matches last auto-generated value
        if (!documentTitle || documentTitle === prevAutoTitle.current) {
            actions.setDocumentTitle(autoTitle);
        }
        prevAutoTitle.current = autoTitle;
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [selectedDocumentType?.name, nachname, vorname]);

    const isAutoGenerated = !!prevAutoTitle.current && documentTitle === prevAutoTitle.current;
    const documentCountryCode = selectedDocumentType?.country_code || "DE";
    const enabledClausesCount = documentClauses.filter(c => c.is_enabled).length;
    const totalClausesCount = documentClauses.length;

    // Magic Fill — Vorschläge aus historischen Dokumenten
    const magicFill = useMagicFill({
        documentTypeId: documentTypeId ?? null,
        countryCode: documentCountryCode,
        enabled: !!documentTypeId,
    });

    const handleMagicFillApply = useCallback(
        (fieldKey: string) => {
            const value = magicFill.applyField(fieldKey);
            if (value !== undefined) {
                actions.updateFormField(fieldKey as keyof typeof state.formData, value);
            }
        },
        [magicFill, actions, state.formData]
    );

    const handleMagicFillApplyAll = useCallback(() => {
        const values = magicFill.applyAll();
        for (const [fieldKey, value] of values) {
            actions.updateFormField(fieldKey as keyof typeof state.formData, value);
        }
    }, [magicFill, actions, state.formData]);

    const handleMagicFillDismiss = useCallback(
        (fieldKey: string) => {
            magicFill.dismissField(fieldKey);
        },
        [magicFill]
    );

    return (
        <div className="h-full flex flex-col overflow-hidden">
            {/* Header — WorkflowDots + Dokumenttitel */}
            <div className="p-4 pb-3 shrink-0 space-y-3">
                <WorkflowDots />
                <Input
                    value={documentTitle}
                    onChange={(e) => {
                        prevAutoTitle.current = ""; // Manual edit disables auto-naming
                        actions.setDocumentTitle(e.target.value);
                    }}
                    placeholder="Dokumenttitel eingeben..."
                    className={cn(
                        "canvas-input text-lg font-semibold h-auto py-2",
                        isAutoGenerated && "doc-name-input auto-generated"
                    )}
                />
                {isAutoGenerated && (
                    <p className="doc-name-hint">
                        Wird automatisch aktualisiert, wenn du Mitarbeiterdaten eingibst.
                    </p>
                )}
            </div>

            {/* Briefpapier-Auswahl */}
            <div className="px-4 py-3">
                <StationeryPicker
                    value={state.userTemplateId}
                    onChange={(id) => {
                        actions.setUserTemplateId(id);
                        if (id) {
                            actions.loadStationeryZones(id);
                        }
                    }}
                    countryCode={documentCountryCode}
                />
            </div>

            {/* Tonalität */}
            <div className="px-4 pb-3">
                <div className="text-2xs font-medium text-[var(--text-tertiary)] uppercase tracking-[0.12em] mb-1.5">
                    Tonalität
                </div>
                <ToneSegmented value={state.toneOfVoice} onChange={actions.setToneOfVoice} />
            </div>

            {/* Scrollbarer Bereich für Sektionen */}
            <ScrollArea className="flex-1 overflow-auto">
                <div className="p-4 space-y-4">
                    {/* Formularfelder - IMMER sichtbar (nicht collapsible) */}
                    <div>
                        <div className="flex items-center gap-2 py-1 mb-1">
                            <Users className="w-3 h-3 text-[var(--text-tertiary)] shrink-0" />
                            <span className="text-2xs font-medium text-[var(--text-tertiary)] uppercase tracking-[0.12em]">Formularfelder</span>
                        </div>
                        <FormFieldsSection
                            countryCode={documentCountryCode}
                            magicFillSuggestions={magicFill.suggestions}
                            magicFillDocumentCount={magicFill.documentCount}
                            onMagicFillApply={handleMagicFillApply}
                            onMagicFillApplyAll={handleMagicFillApplyAll}
                            onMagicFillDismiss={handleMagicFillDismiss}
                        />

                        {/* Dokumenttyp-spezifische Zusatzfelder */}
                        {selectedDocumentType && (
                            <DynamicFieldsSection
                                documentTypeName={selectedDocumentType.name}
                                countryCode={documentCountryCode}
                            />
                        )}
                    </div>

                    {/* Konsistenz- und Compliance-Prüfung */}
                    {state.formData.vorname && state.formData.nachname && (
                        <ConsistencyBanner
                            employeeName={`${state.formData.vorname} ${state.formData.nachname}`}
                            currentFormData={state.formData as unknown as Record<string, unknown>}
                            countryCode={documentCountryCode}
                            documentTypeId={documentTypeId ?? undefined}
                        />
                    )}
                    {state.editorContent && (
                        <ComplianceRiskBanner
                            contentHtml={state.editorContent}
                            countryCode={documentCountryCode}
                        />
                    )}

                    {/* Textbausteine - Kompakter Link mit Modal */}
                    {totalClausesCount > 0 && (
                        <Button
                            variant="ghost"
                            className="w-full justify-between h-auto py-3 px-4 bg-[var(--bg-hover)] hover:bg-[var(--nw-warm-100)] border-0 rounded-[var(--radius-md-ds)] transition-all"
                            onClick={() => setShowClausesModal(true)}
                        >
                            <div className="flex items-center gap-2">
                                <Layers className="w-3.5 h-3.5 text-muted-foreground/40" />
                                <span className="font-medium text-sm">Textbausteine</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <Badge variant="secondary" className="text-[10px] font-normal bg-primary/8 text-primary/70 rounded-full">
                                    {enabledClausesCount}/{totalClausesCount}
                                </Badge>
                                <ChevronRight className="w-3.5 h-3.5 text-muted-foreground/50" />
                            </div>
                        </Button>
                    )}

                    {/* Anlagen - Kompakter Link mit Modal */}
                    {documentTypeId && (
                        <Button
                            variant="ghost"
                            className="w-full justify-between h-auto py-3 px-4 bg-[var(--bg-hover)] hover:bg-[var(--nw-warm-100)] border-0 rounded-[var(--radius-md-ds)] transition-all"
                            onClick={() => setShowAttachmentsModal(true)}
                        >
                            <div className="flex items-center gap-2">
                                <Paperclip className="w-3.5 h-3.5 text-muted-foreground/40" />
                                <span className="font-medium text-sm">Anlagen</span>
                            </div>
                            <div className="flex items-center gap-2">
                                {selectedAttachmentIds.length > 0 && (
                                    <Badge variant="secondary" className="text-[10px] font-normal bg-primary/8 text-primary/70 rounded-full">
                                        {selectedAttachmentIds.length}
                                    </Badge>
                                )}
                                <ChevronRight className="w-3.5 h-3.5 text-muted-foreground/50" />
                            </div>
                        </Button>
                    )}
                </div>
            </ScrollArea>

            {/* Action Bar (fixiert unten) */}
            <ActionBar />

            {/* Textbausteine Modal */}
            <Dialog open={showClausesModal} onOpenChange={setShowClausesModal}>
                <DialogContent className="max-w-2xl max-h-[80vh] overflow-hidden flex flex-col">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2">
                            <Layers className="w-5 h-5 text-primary" />
                            Textbausteine anpassen
                        </DialogTitle>
                    </DialogHeader>
                    <div className="flex-1 overflow-auto py-4">
                        <ClauseSelectionSection />
                    </div>
                </DialogContent>
            </Dialog>

            {/* Anlagen Modal */}
            <Dialog open={showAttachmentsModal} onOpenChange={setShowAttachmentsModal}>
                <DialogContent className="max-w-2xl max-h-[80vh] overflow-hidden flex flex-col">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2">
                            <Paperclip className="w-5 h-5 text-primary" />
                            Anlagen auswählen
                        </DialogTitle>
                    </DialogHeader>
                    <div className="flex-1 overflow-auto py-4">
                        {documentTypeId && (
                            <AttachmentSelector
                                documentTypeId={documentTypeId}
                                selectedIds={selectedAttachmentIds}
                                onSelectionChange={(ids) => {
                                    const currentIds = [...selectedAttachmentIds];
                                    const addedIds = ids.filter(id => !currentIds.includes(id));
                                    const removedIds = currentIds.filter(id => !ids.includes(id));
                                    for (const id of addedIds) actions.toggleAttachment(id);
                                    for (const id of removedIds) actions.toggleAttachment(id);
                                }}
                            />
                        )}
                    </div>
                </DialogContent>
            </Dialog>
        </div>
    );
};

export default LeftControlPanel;
